run: src/*
	python3 -m src.run

test: src/*
	python3 -m pytest

testv: src/*
	python3 -m pytest -v

test-1: src/*
	python3 -m pytest test/part1_test.py

test-2: src/*
	python3 -m pytest test/part2_test.py

test-3: src/*
	python3 -m pytest test/part3_test.py

test-4: src/*
	python3 -m pytest test/part4_test.py

test-5: src/*
	python3 -m pytest test/part5_test.py
